build_script:
- cmd: build.cmd BuildApp
- cmd: build.cmd RunTests
- cmd: build.cmd CreatePackages
test: off
nuget:
    account_feed: true
    project_feed: true
artifacts:
- path: 'packaging/scientist*.nupkg'
  name: ScientistPackages
build:
  verbosity: normal
